spring:
  application:
    name: tlias-web-management


  datasource:
    url: jdbc:mysql://localhost:3306/tlias?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    drive-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: lsr-java
    region: cn-beijing
